version: 2.1
jobs:
  build:
    docker:
      - image: vvakame/review:2.5
    steps:
      - checkout
      - run:
          name: Build PDF
          command: rake clean pdf
          working_directory: ./articles
      - run:
          name: Preparing artifacts
          command: |
            mkdir -p /tmp/artifacts
            cp ./articles/*.pdf /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: /
      - run:
          name: Upload to Dropbox
          command: ./upload_dropbox.sh ./articles/book.pdf ${DROPBOX_TOKEN}
